### ISSUE TITLE
failure to create journey/knowledge statement 

### ISSUE THREAD

**Issue by stappan** [MetaCell/sckan-composer#306] opened 2024-10-05 23:14 UTC
In this composer record: https://composer.scicrunch.io/statement/158 
the journey and knowledge statements are not properly created. 

When examining this in the path builder, it is because there is no destination specified. This did not cause the population to be marked as invalid however. (and should be; see related issue for new feature request.)

**Comment by ddelpiano** [comment] 2024-10-23 13:47
this is a duplicate of the issue we are already looking at with https://github.com/MetaCell/sckan-composer/issues/241, closing this.

**Closed by ddelpiano** 2024-10-23 13:47 UTC
